### ISSUE TITLE
Incorrect matches with multiple rules with numeric conditions

### ISSUE THREAD

**Issue by quickshore** [atlasgurus/rulestone#8]
Multiple rules with simple numeric conditions gives incorrect number of matches. Basically in the test case below all the rules matches:

`func TestMultipleConditionsIssue(t *testing.T) {
	repo := engine.NewRuleEngineRepo()
	_, err := repo.RegisterRuleFromString("expression: age > 20 && age < 30", "yaml")
	if err != nil {
		t.Fatalf("failed RegisterRuleFromString: %v", err)
		return
	}

	_, err = repo.RegisterRuleFromString("expression: age < 20", "yaml")
	if err != nil {
		t.Fatalf("failed RegisterRuleFromString: %v", err)
		return
	}

	_, err = repo.RegisterRuleFromString("expression: age > 30", "yaml")
	if err != nil {
		t.Fatalf("failed RegisterRuleFromString: %v", err)
		return
	}

	genFilter, err := engine.NewRuleEngine(repo)
	if err != nil {
		t.Fatalf("failed NewRuleEngine: %s", err)
	}

	const eventJson string = `{
		"name": "John",
		"age": 25
	}`

	var event map[string]interface{}

	if err := json.Unmarshal([]byte(eventJson), &event); err != nil {
		t.Fatalf("failed Unmarshal: %s", err)
	} else {
		matches := genFilter.MatchEvent(event)
		if len(matches) != 1 {
			t.Fatalf("failed number of matches %d != 1", len(matches))
		}
	}

	if repo.GetAppCtx().NumErrors() > 0 {
		t.Fatalf("failed due to %d errors", repo.GetAppCtx().NumErrors())
		repo.GetAppCtx().PrintErrors()
	}
}`

The result is:

```
=== RUN   TestMultipleConditionsIssue
optimizedAndOrSets removed 0
OrSetsInlined 0
AndOrSetsInlined 0
AndOrSetsGCed 0
    engine_api_test.go:241: failed number of matches 3 != 1
--- FAIL: TestMultipleConditionsIssue (0.00s)

FAIL
```

**Comment by atlasgurus** [comment]
Should be fixed by the following commit.  Also, needed to create a test to reproduce the issue.

commit c0c3532e7eaa41d090cfa6aaa7bc60491f0bef5e (HEAD -> main, origin/main)
Author: Vassili Gorshkov <vassili.gorshkov@atlasgurus.com>
Date:   Fri Oct 6 16:37:55 2023 -0700

    RS0008: include compare operation in caching key for genEvalForCompareOperands
